### PR TITLE
Added Tenniel illustrations

### PR DESCRIPTION
**Pull request by drgrigg**
I've scanned and vectorised all 52 illustrations by John Tenniel for this book and inserted them at the appropriate places in the text. Should this be mentioned in the long-description? I note that it isn't mentioned in the long-description for Wonderland.

### CODE REVIEW

**Comment by acabal** [comment]
Excellent job with the SVGs! Group transforms applied and header information and dimensions perfectly clean. Nice!

I'm going to make a few tweaks to some style as I go through this. What pops out at first is using IDs to target several tables. The tables don't need ID attributes because they are not a portion of the text we want to access with an anchor. Instead we can leverage existing IDs to target specific tables. For example instead of 'table#sum' we can use '#preamble table`.

I also think we want to use `<ol>`s instead of `<table>` in the preamble because those are simply lists of moves and not actual tabular data. However we can use CSS to style the `<ol>`s just like a table might be styled.

I'll work on this a little in the coming few days unless you feel like tackling it. But, you've already done a ton of work on this!

**Comment by drgrigg** [comment]
OK (pity we don't have a mirror-reversed font to use, though!). I'll revert that change.

If I take out this image, do you want me to renumber the following images? I have a tool which will let me do that relatively easily (currently written in Swift, but eventually I'll probably convert it to Python).

As for the SVGs, that's all down to SVGOMG. I finally found the setting which was messing up the optimisation when I used it before. So my workflow is: scan at 1600 or 2400 -> potrace -> some clean-ups using a BBedit textfactory -> SVGOMG.

**Comment by acabal** [comment]
Ah, I didn't think of the mirror reverse effect of the text. Let me think about this a little further before we do anything.

**Comment by acabal** [comment]
I feel like there must be a reverse letter set of Unicode. But if so then font support would certainly be very poor.

**Pull request merged**
